### ISSUE TITLE
Election Comms Strategy : member registration announcement

### ISSUE THREAD

**Issue by Marie-L** [pyladies/project-communications#35]
create artwork for :

- [x] registration announcement
- [x] open call for nominations 
- [x] general campaign announcements

NOTE: colours, layout or copy can be changed. Feedback will be much appreciated. Thanks !

![Student Council Elections EMail Header](https://user-images.githubusercontent.com/27898533/88885846-2be6d500-d231-11ea-8f6d-403dd2f330a2.png)

**Comment by Marie-L** [comment]
![Blue and Orange Campaign Poster](https://user-images.githubusercontent.com/27898533/88885275-1f15b180-d230-11ea-9ac8-4d8cd99348d9.png)

**Comment by Marie-L** [comment]
![Global Council Poster](https://user-images.githubusercontent.com/27898533/88885292-289f1980-d230-11ea-875f-66e6eb200752.png)

**Comment by BethanyG** [comment]
Just putting these here, so we don't have to look them up (_pulled from the elections site_):

**Election Calendar**
-  Open call for Council Member Nominations: August 6, 2020 AoE
-  Council Member Nomination cut-off: August 31, 2020 AoE

-  Voter application cut-off date: **August 31, 2020** AoE

-  Voting **start date:** September 7, 2020 AoE
Voting **end date:** September 18, 2020 AoE

**Comment by Marie-L** [comment]
Thank you @BethanyG 🙏 !

**Comment by BethanyG** [comment]
Suggest for the nomination graphic:
*  _**who do you choose?**_  or _**who's your pick?**_ in place of the  **vote wisely** text.  
*   **Deadline to nominate: 31.08.2020** or  **Deadline: 31.08.2020** or even **Window Closes:31.08.2020** in place of the "voting ends" text.
* would use "Nominations Open 31.08.202" instead of "Nominations are open", since this is a pre-announcement.

And -- I have to say it -- I am not a fan of the pink.  But I am only one old, cranky PyLady...so don't listen to me on that.  😉

**Comment by Marie-L** [comment]
Thanks so much for your feedback @BethanyG 😊! I'll implement your suggestions and will post the updated versions below. Also, regarding the colour - I know what you mean. I chose it because it's used in so many other pyladies graphics but once the final artwork is complete I'll create versions in a variety of colours such as blues, greens, purples etc.

**Comment by BethanyG** [comment]
For the first graphic:

*  Is this also for nominations, or was this one intended for voting? 
*  If nominating/running suggest something like "Put on your shoes and"  R U N or "Stand Up and" L E A D
*  If nominating/running, also suggest the direct URL: http://elections.pyladies.com/pages/apply.html

In fact, as I read/look at these...maybe one should be a CTA for _Nominating_, and the other a CTA for _Declaring_ as a candidate, since we have these two paths?  Would that be too much to put out there?  🤔     What do you think?

**Comment by BethanyG** [comment]
PS - I really like the fonts - especially the big brush V O T E font!  😁

**Comment by BethanyG** [comment]
I just realized that we need to review the nomination and declaration forms.  😱   Guess we need to do that in the next 8 days....oops.

**Comment by BethanyG** [comment]
Also - and I do NOT want to create stress or extra work.  But in [this](https://github.com/pyladies/pyladies-elections-website/issues/2) issue we've had volunteers step forward to translate the election site.  I wonder if we should put a call out on Slack or in that issue for some translations for these announcements as well?  Not for this very first round - but maybe for some we post in  few days/in a week?

**Comment by Marie-L** [comment]
Thanks again @BethanyG ! All of the graphics can be used for any milestone (initially I was focusing on mainly the design rather that the content). Yes, I agree we should have two different CTA's for each pathway. Here's a list below of the final artwork I need to finish:
1. CTA for Declaring as a candidate
2. CTA for Nominating
3. CTA to vote

What do you think ?

**Comment by Marie-L** [comment]
@BethanyG re translation for the election site, great idea! Thanks for commenting on the issue! I'll post in slack too

**Comment by BethanyG** [comment]
@Marie-L  - that looks great for categories. 🌟 🎉  

For voting in particular, we may want some additional variants for poking people to register...and then poking them again.  Just because it's always a push to get attention around that.

 And we may want to consider some variants that are super general and just say --
 _Hey!  Did you know?? We're having this election thing!  It's our first one!  Get involved!_   
and
 _Do you know how great PyLadies is?  We're having this election - it's our first one!  Join and get involved!_

But those three you have are the most important to get out there.

 ..  Once we do, we have time to iterate on other versions/variants  😄

**Comment by Marie-L** [comment]
![inaugural_election](https://user-images.githubusercontent.com/27898533/88983938-37371080-d2c4-11ea-937f-47b0c40ed733.png)

**Comment by Marie-L** [comment]
![Global Council Poster (1)](https://user-images.githubusercontent.com/27898533/88983959-41590f00-d2c4-11ea-9c9f-d75fcde8be7e.png)

**Comment by Marie-L** [comment]
![Global Council Poster_self_nominate](https://user-images.githubusercontent.com/27898533/88984271-14f1c280-d2c5-11ea-8c48-bb274969ff2f.png)
![Global Council Poster_self_nominate (1)](https://user-images.githubusercontent.com/27898533/88984276-18854980-d2c5-11ea-88db-1ccdba5af5a1.gif)

**Comment by BethanyG** [comment]
Have a couple of ideas ... if you don't mind me proposing?  I'll post them here by EOD my time.

**Comment by BethanyG** [comment]
![RUN_III](https://user-images.githubusercontent.com/5923094/88996929-4b1e4a80-d2a3-11ea-8e20-7c8b6207e6ba.png)
![RUN_II](https://user-images.githubusercontent.com/5923094/88996941-4f4a6800-d2a3-11ea-864e-916871cc3d7a.png)
![RUN](https://user-images.githubusercontent.com/5923094/88996948-52ddef00-d2a3-11ea-9f1c-4869f6b67d4c.png)

**Comment by BethanyG** [comment]
..I have a bunch of shoe vectors, if you want to use any of them.

**Comment by Marie-L** [comment]
@BethanyG Love this!! Please send me the sneaker vectors so I can make animated versions too 😊

**Comment by Marie-L** [comment]
@BethanyG I've posted the first announcement (on all platforms including LinkedIn) and I'm in the process of finishing the necessary graphics for next week. I will share an update here tomorrow

**Comment by Marie-L** [comment]
![having_an_election](https://user-images.githubusercontent.com/27898533/89218986-e32f7300-d5c6-11ea-9bc4-6ddd7ffa210d.gif)
![having_an_election_green](https://user-images.githubusercontent.com/27898533/89219005-edea0800-d5c6-11ea-8804-136fc1e5e019.gif)

**Comment by Marie-L** [comment]
![run poster](https://user-images.githubusercontent.com/27898533/89219050-00644180-d5c7-11ea-9738-d7d092e2255f.gif)
![run poster 2](https://user-images.githubusercontent.com/27898533/89219056-035f3200-d5c7-11ea-97f0-1bd16861500a.gif)

**Comment by Marie-L** [comment]
![_inaugural_election_blue](https://user-images.githubusercontent.com/27898533/89219253-576a1680-d5c7-11ea-9932-a99a265d3599.gif)

**Comment by Marie-L** [comment]
@BethanyG I've created a few more variations based on your designs (they're not exactly the same so let me know if you want anything changed or added). I'm planning to post the "inaugural" & "we're having a.." graphics every day until Thursday. Then will switch to the open call graphics (and will add more color variations).

Also, if you have more suggestion for copy, please share ( I'm planning to use one you wrote before "_Did you know?? We're having this election thing! It's our first one! Get involved!"_

Or maybe it would be good to post the gif with the link and no copy, what do you think ?

**Comment by BethanyG** [comment]
Hi @Marie-L  - Thank you for your work on these!!

I really like these green and blue "We're having an election" graphics!  We might want to try a variant  with the Pylady outline either in black or Dk. Blue or yellow -- just to make her stand out a bit & shake things up...but I dunno if that is doing to be to "loud" or not.  

For the "Put on your shoes & RUN" ... I hate to be picky, but for some reason today that darker pink ampersand is making my eyes bounce around....dunno if that is because it's smaller and brighter ... or if it's the addition of that darker navy for the date, which has a similar weight....something feels out of balance there.  Might want to try a larger ampersand and have the two match in color -- either that dark pink, the navy, or the turquoise.  Or maybe even the brownish color from the shoe creases??  Dunno.  I can try a variant here in a few minutes.

**Comment by BethanyG** [comment]
![image](https://user-images.githubusercontent.com/5923094/89234456-de57c880-d5a0-11ea-9dee-a5b654b800ff.png)


![RUN_VII](https://user-images.githubusercontent.com/5923094/89234949-098ee780-d5a2-11ea-99e9-c50a62d33ad1.png)

**Comment by BethanyG** [comment]
![RUN_VIII](https://user-images.githubusercontent.com/5923094/89235122-799d6d80-d5a2-11ea-8060-8f20450bfac4.png)

**Comment by Marie-L** [comment]
@BethanyG Thank for your feedback and for all your work too !! I've just created a canva for our team and have invited you to edit, have you received the invitation? I've started adding the files from my personal account (so far there's only 3) but at least we can start working from the same workspace. I'll finish adding everything tomorrow. Thanks again 😊🙏

**Comment by BethanyG** [comment]
![Run with shoes](https://user-images.githubusercontent.com/5923094/89240730-d3f1fa80-d5b1-11ea-82f6-4c77e0292492.png)

**Comment by BethanyG** [comment]
![Run with shoes_II](https://user-images.githubusercontent.com/5923094/89241330-6e067280-d5b3-11ea-9bff-3316c605a5ce.png)

**Comment by Marie-L** [comment]
@BethanyG Love it !

**Comment by Marie-L** [comment]
I'll close this issue as the work has now been completed.
